language: scala

jdk: oraclejdk8

scala:
   - 2.12.2

before_install:
- npm cache clean --force
- npm install

deploy:
  provider: heroku
  app: play-react-test
  api_key:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAABAQDcCHtIbWATPlWbwRlr1gxNhpO8LaotptKX1N813O28prSVtE9TfoB/xyCjFv+s32+$